#!/bin/sh
### BEGIN INIT INFO
# Provides:          caterpillar
# Required-Start:    $networking
# Required-Stop:     $networking
# Should-Start:      $named
# Should-Stop:       $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: caterpillar
# Description:       caterpillar
### END INIT INFO



ERL_LIBS="ERL_LIBS /var/lib/caterpillar/:/var/lib/smprc/erlang/"
ERL=$(which erl)
ETC_PATH="/etc/caterpillar"
CONFIG="$ETC_PATH/caterpillar.config"


START_STOP="start-stop-daemon --chuid caterpillar:caterpillar \
    --chdir /var/lib/caterpillar \
    --exec $ERL --start --"


OPTS="-setcookie caterpillar +W w +K true"

usage()
{
    echo "caterpillar {start|stop|restart|status|attach}"
}


start()
{
    echo "starting"
    $START_STOP -env $ERL_LIBS $OPTS -config $CONFIG \
        -noshell -noinput -detached -shutdown_time 500 -boot start_sasl -s caterpillar_app
}


restart()
{
    stop
    sleep 1
    start
}


attach()
{   
    echo "attaching"
    erl -env $ERL_LIBS \
        -setcookie $(caterpillar.escript $CONFIG cookie) \
        -name attach_master_$$@127.0.0.1 \
        -remsh $(caterpillar.escript $CONFIG self)

}

stop()
{
    echo "stopping"
    erl -env $ERL_LIBS \
        -setcookie $(caterpillar.escript $CONFIG cookie) \
        -noshell -noinput \
        -name ctl_caterpillar_$$@127.0.0.1 \
        -s caterpillar_app stop_node $(caterpillar.escript $CONFIG self) \
        -s init stop
}


status()
{
    echo "requesting status"
    erl -env $ERL_LIBS \
        -setcookie $(caterpillar.escript $CONFIG cookie) \
        -noshell -noinput \
        -name ctl_caterpillar_$$@127.0.0.1 \
        -s caterpillar_app status_node $(caterpillar.escript $CONFIG self) \
        -s init stop
}

command()
{
    case $1 in
        start|stop|status|restart|attach)
            eval $1
        ;;
        *)
        usage
    esac
}

if [ $# = 1 ]; then
    command $1
else
    usage
fi
